import os

def write_html():
    lines = []
    lines.append("<!DOCTYPE html>")
    lines.append('<html lang="zh-CN">')
    lines.append("<head>")
    lines.append('<meta charset="UTF-8">')
    lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    lines.append("<title>AI内容工坊</title>")
    lines.append("<style>")
    lines.append("*{margin:0;padding:0;box-sizing:border-box}")
    lines.append('body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f5f5f7;color:#1d1d1f;line-height:1.6}')
    lines.append(".container{max-width:960px;margin:0 auto;padding:0 20px}")
    lines.append(".hero{background:linear-gradient(135deg,#1d1d1f,#2d2d2f);color:#fff;padding:80px 0 60px;text-align:center}")
    lines.append(".hero h1{font-size:2.8rem;font-weight:700;margin-bottom:12px}")
    lines.append(".hero p{font-size:1.15rem;color:#a1a1a6;max-width:600px;margin:0 auto 28px}")
    lines.append('.hero .badge{display:inline-block;background:#0071e3;color:#fff;padding:6px 16px;border-radius:20px;font-size:.85rem;font-weight:500;margin-bottom:20px}')
    lines.append('.cta-btn{display:inline-block;background:#0071e3;color:#fff;padding:14px 36px;border-radius:30px;font-size:1.05rem;font-weight:600;text-decoration:none;border:none;cursor:pointer}')
    lines.append(".cta-btn:hover{background:#0077ed}")
    lines.append(".cta-btn.secondary{background:transparent;border:1.5px solid rgba(255,255,255,.4);margin-left:12px}")
    lines.append(".section{padding:60px 0}")
    lines.append(".section-title{font-size:1.8rem;font-weight:700;text-align:center;margin-bottom:40px}")
    lines.append(".services-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:20px}")
    lines.append(".service-card{background:#fff;border-radius:16px;padding:28px;box-shadow:0 2px 8px rgba(0,0,0,.04);transition:transform .2s}")
    lines.append(".service-card:hover{transform:translateY(-3px);box-shadow:0 8px 24px rgba(0,0,0,.08)}")
    lines.append(".service-card .icon{font-size:2rem;margin-bottom:12px}")
    lines.append(".service-card h3{font-size:1.15rem;font-weight:600;margin-bottom:8px}")
    lines.append(".service-card p{font-size:.92rem;color:#6e6e73}")
    lines.append(".service-card .price{display:inline-block;margin-top:14px;font-weight:600;color:#0071e3;font-size:1rem}")
    lines.append(".pricing-table{background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.04)}")
    lines.append(".pricing-table table{width:100%;border-collapse:collapse}")
    lines.append(".pricing-table th{background:#f5f5f7;padding:14px 20px;text-align:left;font-weight:600;font-size:.9rem;color:#6e6e73}")
    lines.append(".pricing-table td{padding:14px 20px;border-bottom:1px solid #eee;font-size:.95rem}")
    lines.append(".pricing-table tr:last-child td{border-bottom:none}")
    lines.append('.pricing-table .tag{display:inline-block;background:#e8f5e9;color:#2e7d32;padding:2px 10px;border-radius:12px;font-size:.8rem;font-weight:500}')
    lines.append(".inquiry-section{background:#fff;border-radius:16px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,.04);max-width:600px;margin:0 auto}")
    lines.append(".form-group{margin-bottom:18px}")
    lines.append(".form-group label{display:block;font-weight:600;font-size:.9rem;margin-bottom:6px}")
    lines.append(".form-group input,.form-group select,.form-group textarea{width:100%;padding:12px 14px;border:1.5px solid #d2d2d7;border-radius:10px;font-size:.95rem;font-family:inherit}")
    lines.append(".form-group input:focus,.form-group select:focus,.form-group textarea:focus{outline:none;border-color:#0071e3}")
    lines.append(".form-group textarea{resize:vertical;min-height:100px}")
    lines.append('.submit-btn{width:100%;padding:14px;background:#0071e3;color:#fff;border:none;border-radius:12px;font-size:1rem;font-weight:600;cursor:pointer}')
    lines.append(".submit-btn:hover{background:#0077ed}")
    lines.append(".why-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:20px}")
    lines.append(".why-item{text-align:center;padding:20px}")
    lines.append(".why-item .num{font-size:2.2rem;font-weight:700;color:#0071e3;margin-bottom:4px}")
    lines.append(".why-item p{font-size:.92rem;color:#6e6e73}")
    lines.append(".faq-item{background:#fff;border-radius:12px;padding:20px 24px;margin-bottom:10px;box-shadow:0 1px 4px rgba(0,0,0,.04)}")
    lines.append(".faq-item q{font-weight:600;display:block;margin-bottom:6px}")
    lines.append(".faq-item a{color:#6e6e73;font-size:.92rem}")
    lines.append(".footer{text-align:center;padding:40px 0;color:#6e6e73;font-size:.85rem;border-top:1px solid #d2d2d7;margin-top:20px}")
    lines.append(".toast{position:fixed;bottom:30px;left:50%;transform:translateX(-50%);background:#1d1d1f;color:#fff;padding:14px 28px;border-radius:12px;font-size:.95rem;opacity:0;transition:opacity .3s;pointer-events:none;z-index:999}")
    lines.append(".toast.show{opacity:1}")
    lines.append("@media(max-width:640px){.hero h1{font-size:1.8rem}.cta-btn.secondary{margin-left:0;margin-top:10px;display:block}}")
    lines.append("</style>")
    lines.append("</head>")
    lines.append("<body>")
    lines.append('<div class="hero"><div class="container">')
    lines.append('<div class="badge">今日下单 / 2小时内交付</div>')
    lines.append("<h1>AI 内容工坊</h1>")
    lines.append("<p>不做模板糊弄。每份交付都由 AI + 人工精修，<br>比你自己写的快 10 倍，比纯 AI 的有温度 10 倍。</p>")
    lines.append('<a href="#inquiry" class="cta-btn">立即下单</a>')
    lines.append('<a href="#pricing" class="cta-btn secondary">查看报价</a>')
    lines.append("</div></div>")
    lines.append('<div class="section"><div class="container">')
    lines.append('<h2 class="section-title">能做什么</h2>')
    lines.append('<div class="services-grid">')
    lines.append('<div class="service-card"><div class="icon">&#9998;</div><h3>文案代写</h3><p>小红书笔记、公众号文章、朋友圈文案、品牌故事。</p><div class="price">20-100 / 篇</div></div>')
    lines.append('<div class="service-card"><div class="icon">&#128196;</div><h3>文档代做</h3><p>PPT、Word排版、简历优化、商业计划书、读书笔记、演讲稿。</p><div class="price">30-200 / 份</div></div>')
    lines.append('<div class="service-card"><div class="icon">&#127912;</div><h3>AI 绘图</h3><p>头像设计、海报、配图、产品图、LOGO概念稿。</p><div class="price">15-80 / 张</div></div>')
    lines.append('<div class="service-card"><div class="icon">&#128202;</div><h3>数据分析</h3><p>Excel报表、数据可视化、Python脚本、自动化工具。</p><div class="price">50-300 / 单</div></div>')
    lines.append('<div class="service-card"><div class="icon">&#128241;</div><h3>小红书代运营</h3><p>账号定位、选题规划、笔记撰写、排期发布、数据复盘。</p><div class="price">499-1999 / 月</div></div>')
    lines.append('<div class="service-card"><div class="icon">&#127916;</div><h3>视频脚本</h3><p>抖音口播、B站干货、小红书 Vlog 脚本。</p><div class="price">30-150 / 条</div></div>')
    lines.append("</div></div></div>")
    lines.append('<div class="section" style="background:#f5f5f7"><div class="container">')
    lines.append('<h2 class="section-title">标准报价</h2>')
    lines.append('<div class="pricing-table"><table>')
    lines.append("<thead><tr><th>服务项</th><th>说明</th><th>价格</th></tr></thead>")
    lines.append("<tbody>")
    lines.append('<tr><td>小红书笔记</td><td>500-800字 + 标题 + emoji排版 + 话题标签</td><td><strong>29</strong> <span class="tag">最热</span></td></tr>')
    lines.append("<tr><td>公众号文章</td><td>1500-2000字，含小标题和配图建议</td><td><strong>59</strong></td></tr>")
    lines.append("<tr><td>短视频脚本</td><td>60s口播稿，含开头钩子+逻辑框架+CTA</td><td><strong>39</strong></td></tr>")
    lines.append("<tr><td>简历优化</td><td>中英文简历排版+措辞润色+一页纸优化</td><td><strong>49</strong></td></tr>")
    lines.append("<tr><td>PPT制作</td><td>10页以内，模板精美，含动画/图表</td><td><strong>99</strong></td></tr>")
    lines.append("<tr><td>AI 头像/人像</td><td>Midjourney直出，含3版供选</td><td><strong>19</strong></td></tr>")
    lines.append("<tr><td>Excel 自动化</td><td>VBA脚本/Python脚本，去重/合并/报表一键出</td><td><strong>69</strong></td></tr>")
    lines.append('<tr><td>定制方案</td><td>商业计划书、毕业论文润色、品牌全案</td><td><strong>200+</strong> <span class="tag" style="background:#fff3e0;color:#e65100">议价</span></td></tr>')
    lines.append("</tbody></table></div>")
    lines.append('<p style="text-align:center;margin-top:16px;color:#6e6e73;font-size:.9rem">量大优惠 / 长期合作可谈套餐价</p>')
    lines.append("</div></div>")
    lines.append('<div class="section"><div class="container">')
    lines.append('<h2 class="section-title">为什么找我</h2>')
    lines.append('<div class="why-grid">')
    lines.append("<div class=\"why-item\"><div class=\"num\">2h</div><p>平均交付时间<br>急单最快30分钟</p></div>")
    lines.append('<div class="why-item"><div class="num">&infin;</div><p>免费修改<br>改到满意为止</p></div>')
    lines.append('<div class="why-item"><div class="num">100%</div><p>原创承诺<br>AI查重通过再交付</p></div>')
    lines.append('<div class="why-item"><div class="num">OK</div><p>先出稿，满意再付款<br>无风险合作</p></div>')
    lines.append("</div></div></div>")
    lines.append('<div class="section" style="background:#f5f5f7"><div class="container">')
    lines.append('<h2 class="section-title">常见问题</h2>')
    lines.append("<div class=\"faq-item\"><q>怎么下单？</q><a>直接填下面的表单，或者加微信联系。做完先发你看，满意再付款。</a></div>")
    lines.append("<div class=\"faq-item\"><q>多久能出稿？</q><a>常规单 2 小时内交付。急单加急 30 分钟搞定，不额外收费。</a></div>")
    lines.append("<div class=\"faq-item\"><q>能保证原创吗？</q><a>每份交付都经过 AI 查重检测，原创率 90% 以上。</a></div>")
    lines.append("<div class=\"faq-item\"><q>不满意怎么办？</q><a>不限次数修改，改到你满意为止。实在不满意，分文不收。</a></div>")
    lines.append("</div></div>")
    lines.append('<div class="section"><div class="container">')
    lines.append('<h2 class="section-title">提交需求</h2>')
    lines.append('<form class="inquiry-section" id="orderForm">')
    lines.append('<div class="form-group"><label>怎么称呼你</label><input type="text" id="name" placeholder="你的名字 / 昵称" required></div>')
    lines.append('<div class="form-group"><label>联系方式</label><input type="text" id="contact" placeholder="微信 / 手机 / 邮箱" required></div>')
    lines.append('<div class="form-group"><label>服务类型</label><select id="serviceType" required>')
    lines.append('<option value="">请选择...</option>')
    lines.append('<option value="小红书笔记">小红书笔记</option>')
    lines.append('<option value="公众号文章">公众号文章</option>')
    lines.append('<option value="短视频脚本">短视频脚本</option>')
    lines.append('<option value="简历优化">简历优化</option>')
    lines.append('<option value="PPT制作">PPT制作</option>')
    lines.append('<option value="AI头像">AI头像/人像</option>')
    lines.append('<option value="Excel自动化">Excel自动化</option>')
    lines.append('<option value="代运营">小红书代运营</option>')
    lines.append('<option value="其他">其他（备注说明）</option>')
    lines.append("</select></div>")
    lines.append('<div class="form-group"><label>详细需求</label><textarea id="detail" placeholder="说一下具体要求：什么主题？多少字？什么风格？什么时候要？" required></textarea></div>')
    lines.append('<button type="submit" class="submit-btn">提交需求 / 免费报价</button>')
    lines.append("</form></div></div>")
    lines.append('<div class="footer"><div class="container">')
    lines.append("<p>2026 AI内容工坊 / 先出稿，满意再付款</p>")
    lines.append('<p style="margin-top:4px">微信: your_wechat_id_here</p>')
    lines.append("</div></div>")
    lines.append('<div class="toast" id="toast"></div>')
    lines.append("<script>")
    lines.append("(function(){")
    lines.append('var form=document.getElementById("orderForm");if(!form)return;')
    lines.append('form.addEventListener("submit",function(e){')
    lines.append("e.preventDefault();")
    lines.append('var name=document.getElementById("name").value.trim();')
    lines.append('var contact=document.getElementById("contact").value.trim();')
    lines.append('var service=document.getElementById("serviceType").value;')
    lines.append('var detail=document.getElementById("detail").value.trim();')
    lines.append("if(!name||!contact||!service||!detail)return;")
    lines.append('var orders=JSON.parse(localStorage.getItem("orders")||"[]");')
    lines.append("orders.unshift({name:name,contact:contact,service:service,detail:detail,time:new Date().toLocaleString()});")
    lines.append('localStorage.setItem("orders",JSON.stringify(orders));')
    lines.append('var toast=document.getElementById("toast");')
    lines.append('toast.textContent="需求已保存！复制信息发给我";')
    lines.append('toast.classList.add("show");')
    lines.append("setTimeout(function(){toast.classList.remove(\"show\")},3000);")
    lines.append('var txt="客户: "+name+"\\n联系方式: "+contact+"\\n服务: "+service+"\\n需求: "+detail;')
    lines.append("var ta=document.createElement(\"textarea\");")
    lines.append("ta.value=txt;")
    lines.append('ta.style.position="fixed";ta.style.opacity="0";')
    lines.append("document.body.appendChild(ta);ta.select();")
    lines.append('document.execCommand("copy");')
    lines.append("document.body.removeChild(ta);")
    lines.append("form.reset();")
    lines.append("});})();")
    lines.append("</script>")
    lines.append("</body>")
    lines.append("</html>")

    content = "\n".join(lines)
    path = r"C:\Users\25495\Desktop\新建文件夹\startup-kit\index.html"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("OK size:", len(content))

write_html()
